House/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', dashboard, name="dashboard"),
    path('estate_create/', EstateCreate.as_view(), name="estate_create"),
    path('estate_list/', EstateListView.as_view(), name="estate_list"),
    path('<estate_name>/', estate_detail, name='estate_detailing'),
    path('estate_edit/edit', EstateEdit.as_view(), name='estate_edit'),
    path('estate_delete/<pk>', EstateDeleteView, name='estate_delete'),
    path('<estate_id>/<pk>', block_details, name='block_details'),

    #apartment
    path('rooms/<flat_id>/', apartment_room_details, name='room_det'),
    path('<flat_id>/apartment_update/', apartment_update, name='apartment_update'),
    path('apartment/<estate_name>/', apartment_list, name='apartment_list'),
    path('apartment/estate_csv/myestatecsv', estate_csv, name='estate_csv'),
    path('apartment/apartment_csv/<estate_name>', apartment_csv, name='apartment_csv'),
    path('apartment/estate_list/estate-apartment', estate_list, name='estate_listing'),

    #testing apartment
    path('<apartment_pk>/apartment_testing/', apartment_test, name='apartment_test'),
    path('apartment/<flat_id>/apartd', apartment_room_test, name='apartment_room_test'),

    #rooms
    path('rooms/<room_id>/rooms', room_update, name='room_update'),
    path('rooms/<room_id>/rooms_detail', room_detail, name='room_detail'),
    path('rooms/<room_pk>/rooms_detail_main', room_detail_main, name='room_details'),
    path('rooms/rooms_update/<room_pk>', room_update_2, name='room_detail_update'),
    path('\\room', room_list, name='room_list'),
]

Rent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from customer.views import *

urlpatterns = [
    path("", home, name="home"),
    path('admin/', admin.site.urls),
    path('estate/', include('House.urls')),
    path('customer/', include('customer.urls')),
    path('payment/', include('payment.urls')),
    path('cart/', include('cart.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

House/models.py
from email.policy import default
from django.db import models
import re
from PIL import Image
from django.urls import reverse


class City(models.Model):
    
    citys = models.CharField(max_length=20, unique=True)
    image = models.ImageField(upload_to='city', blank=True, null=True)
    status = models.CharField(default=0, editable=False, max_length=1)

    def __str__(self):
        return self.citys


class Estate(models.Model):
    estate_name = models.CharField(max_length=100, unique=True, help_text="enter a valid apartment name",)
    image = models.ImageField(upload_to='uploads/post_photos', blank=True, null=True, default="download_6mOeWlD.jfif")
    city = models.CharField(max_length=20)
    location = models.CharField(max_length=40)
    description = models.TextField()
    is_featured = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.estate_name

    def estate_names(self):
        return self.estate_name

    def estate_delete(self):
        if Estate.objects.delete():
            Block.objects.filter(estate_names=self.estate_name)
            Apartment.objects.filter(estate_name=self.estate_name)
            Room.objects.filter(apartment_name_rooms=self.estate_name)
        else:
            pass

    def new_apartment_name(self):
        apartment = self.estate_name
        apartment = str(apartment)

        apartment = re.split('\s+', apartment)

        new = []
        for new_apartment in apartment:
            if len(new_apartment) >= 1:
                new_apartment = new_apartment[0]
                new.append(new_apartment)

        new = "".join(new)
        new = new.upper()
        return new

    def save(self, *args, **kwargs):
        self.new_apartment_name
        self.estate_name
        self.image = self.image
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)
        
        if img.height > 450 and img.width > 500:
            output_size = (450, 500)
            img.thumbnail(output_size)
            img.save(self.image.path)

    class Meta:
        verbose_name_plural = "Estates"
        ordering = ("estate_name",)

    def get_absolute_url(self):
        return reverse("block_details", kwargs={"estate_names_id": self.estate_id, 'pk': self.pk})


class Block(models.Model):
    estate_names = models.ForeignKey(Estate, on_delete=models.CASCADE)
    block_no = models.CharField(max_length=2, null=False, blank=False)
    total_flat = models.CharField(max_length=10, null=True, blank=False)

    def __str__(self):
        return self.block_no

    @property
    def total_flat_no(self):
        return self.total_flat

    def save(self, *args, **kwargs):
        self.total_flat_no

        apartment = self.estate_names
        apartments = str(apartment)

        apartments = re.split('\s+', apartments)

        new = []
        for new_apartments in apartments:
            if len(new_apartments) >= 1:
                new_apartments = new_apartments[0]
                new.append(new_apartments)

        new = "".join(new)
        new = new.upper()

        total_flats = int(self.total_flat)

        triple = []
        for i in range(1, (total_flats) + 1):
            signle = new + self.block_no + "|" + str(i)
            triple.append(signle)

        values = triple

        apart = []

        for i in values:
            estate_name = self.estate_names
            block = self.block_no
            location = self.estate_names.location
            city = self.estate_names.city
            flat = i
            apart.append(Apartment(estate_name=estate_name, block=block, flat_id=flat))

        Apartment.objects.bulk_create(apart)
        super().save(*args, **kwargs)


class Apartment(models.Model):
    types = (
        ('S', 'Shared Apartment'), ('X', 'Exclusive Apartment')
    )

    flat_types = (
        ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')
    )

    estate_name = models.CharField(max_length=20, null=True, blank=True)
    block = models.CharField(max_length=20, null=True, blank=True)
    flat_id = models.CharField(max_length=20, null=True, blank=True)
    apartment_type = models.CharField(max_length=20, choices=types, default=[0][0])
    bedroom_type = models.CharField(max_length=20, choices=flat_types)
    apartment_image = models.ImageField(upload_to='apartment/', null=True)

    def __str__(self):
        return self.flat_id

    class Meta:
        ordering = ("flat_id",)

    def save(self, *args, **kwargs):

        flat_id = self.flat_id

        room = int(self.bedroom_type)

        rooms = []
        for room in range(1, room+1):
            new_list = flat_id + '|' + str(room)
            rooms.append(new_list)

        roomsss = Room.objects.filter(flat_id_rooms=flat_id).all()

        room_list = []
        for room in rooms:
            room_list.append(Room(apartment_name_rooms=self.estate_name, blocks=self.block, 
                                  flat_id_rooms=self.flat_id, room_id=room, apartment_type=self.apartment_type,
                                  bedroom_type=self.bedroom_type))

        if Room.objects.exists():
            roomsss.delete()
            Room.objects.bulk_create(room_list)
        else:
            Room.objects.bulk_create(room_list)
        super().save(*args, **kwargs)


class Room(models.Model):
    type_rooms = (
        ('Executives', 'executives'), ('Standard', 'standard'), ('Mini', 'mini'), ('Deluxe', 'deluxe')
    )

    status = (
        ('available', 'available'), ('expired', 'expired'), ('terminated', 'terminated'), ('running', 'running')
    )
    
    types = (
        ('S', 'Shared Apartment'), ('X', 'Exclusive Apartment')
    )

    flat_types = (
        ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')
    )

    apartment_name_rooms = models.CharField(max_length=50, null=True, blank=True, editable=False)
    blocks = models.CharField(max_length=10, null=True, blank=True, editable=False)
    flat_id_rooms = models.CharField(max_length=10, null=True, blank=True, editable=False)
    apartment_type = models.CharField(max_length=20, choices=types, default=[0][0], editable=False)
    bedroom_type = models.CharField(max_length=20, choices=flat_types)
    room_id = models.CharField(max_length=20, null=True, blank=True)
    room_types = models.CharField(max_length=15, null=False, blank=False, choices=type_rooms)
    capacity = models.SmallIntegerField(default=0)
    ammenities = models.TextField()
    image1 = models.FileField(upload_to='uploads/post_photos', blank=True, null=True)
    unique_room_id = models.CharField(max_length=20, null=True, editable=True, blank=True)
    rent = models.FloatField()
    service_charge = models.FloatField()
    power_charge = models.FloatField()
    price = models.FloatField(editable=False)
    occupied = models.CharField(default="available", choices=status, max_length=10)
    active = models.BooleanField(default=False)
    is_featured = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Room'
        abstract = False
        ordering = ("apartment_name_rooms",)

    def room_save(self):
        return self.occupied

    def room_occupied(self):
        return self.occupied

    def save(self, *args, **kwargs):
        self.unique_room_id = self.room_id + self.room_types[0]
        self.unique_room_id
        self.price = self.rent + self.service_charge + self.power_charge
        self.price
        self.occupied
        self.room_save
        

        super().save(*args, **kwargs)

    def __str__(self):
        return self.flat_id_rooms


class Testemonial(models.Model):
    name = models.CharField(max_length=20)
    content = models.TextField()
    images = models.ImageField(upload_to='testemonials', null=True, blank=True)

    def __str__(self):
        return self.content

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.images.path)

        if img.height > 450 and img.width > 500:
            output_size = (450, 500)
            img.thumbnail(output_size)
            img.save(self.images.path)

House/forms.py
from cgitb import lookup
from django import forms
from .models import *
from django.forms import inlineformset_factory
import django_filters
from django.forms import ClearableFileInput


class EstateForm(forms.ModelForm):
    
    class Meta:
        model = Estate
        exclude = ()


BlockFormset = inlineformset_factory(
    Estate, Block, extra=1, fields="__all__", can_delete=False, max_num=5
)


# ApartmentImageFormset = inlineformset_factory(
#     Apartment, ApartmentImage, form=ApartmentForm, fields="__all__", extra=1, can_delete=False
# )

class ApartmentForm(forms.ModelForm):
    class Meta:
        model = Apartment
        fields = ("apartment_type", "bedroom_type", "apartment_image")


class ApartmentFilter(django_filters.FilterSet):
    block = django_filters.AllValuesFilter()
    flat_id = django_filters.AllValuesFilter()
    apartment_type = django_filters.AllValuesFilter()

    class Meta:
        model = Apartment
        fields = ["flat_id"]


class RoomFilter(django_filters.FilterSet):
    apartment_name_rooms = django_filters.AllValuesFilter(lookup_expr='exact')
    blocks = django_filters.AllValuesFilter()
    room_id = django_filters.AllValuesFilter()

    class Meta:
        model = Room
        fields = ["apartment_name_rooms"]


class EstateFilter(django_filters.FilterSet):
    estate_name = django_filters.AllValuesFilter(lookup_expr='exact')
    location = django_filters.AllValuesFilter()
    city = django_filters.AllValuesFilter()

    class Meta:
        model = Estate
        fields = ["city"]


class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ("room_types", "capacity", "ammenities", "image1", "rent", "service_charge", "power_charge")
        

class ApartmentLevel(forms.ModelForm):
    apartment_type = django_filters.AllValuesFilter()
    
    class Meta:
        model = Apartment
        fields = ['bedroom_type']
        
        
        

House/templates/rooms/apartment_detail.html
{% extends 'Dashboard/base.html' %}

{% block content %}
    {% if messages %}
            {% for message in messages %}
                <div class="text-center alert alert-{{ message.tags }}" id="msg">
                    {{ message|safe }}
                </div>
            {% endfor %}
    {% endif %}
<div class="card-header">
    <a href="{% url 'estate_list' %}" style="text-decoration: none;">{{estate|upper }}</a>
</div>

    <div class="row mt-4">
        {% if estate.block_set.all %}
            {% for block in estate.block_set.all %}
            <div class="col-sm-4">
                <div class="card mb-4">
                    <a href="{% url 'block_details' estate.pk block.pk %}" style="text-decoration: none;">
                    <div class="card-body text-center">
                    <br> Block {{ block|upper }}<br>
                    Total Flat {{ block.total_flat }}
                    </div>
                    </a>

                </div>
            </div>
            {% endfor %}
        {% else %}
        <p> {{msg}}</p>
        {% endif %}

</div>
<script>
    setTimeout(function(){
        if ($('#msg').length > 0) {
            $('#msg').remove();
        }
        
    }, 2000);
</script>

{% endblock content %}

House/templates/rooms/apartment_list.html
{% extends 'Dashboard/base.html' %}
{% load static %}
{% block content %}

{% if messages %}
        {% for message in messages %}
            <div class="text-center alert alert-{{ message.tags }}" id="msg">
                {{ message|safe }}
            </div>
        {% endfor %}
 {% endif %}
 {% if estate %}
    <h3> Estate List </h3>
    <div class="row">
        {% for apartment in estate %}
        <div class="col-sm-4 mt-4">
            <div class="card text-center" style="border-radius: 40px; background-image: url({% static 'media/download.jfif' %}) height: 100px">
                <a href="{% url 'estate_detailing' apartment %}" style="text-decoration: none;">
                    <div class="card-body">
                        <h4> {{ apartment }} </h4>
                        <p> {{apartment.location }}
                        <p>
                        Total Block {{apartment.block_set.count}}
                    </p>
                    </div>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
        <h2 class="card-header"> Estate List </h2>
        {% if apartment.delete %}
            <p class="card-body"> All apartment have been deleted </p>
        {% else %}
            <p class="card-body"> No Estate for now </p>
        {% endif %}
    {% endif %}

<script>
    setTimeout(function(){
        if ($('#msg').length > 0) {
            $('#msg').remove();
        }
        
    }, 2000);
</script>
{% endblock %}

House/templates/rooms/apartment_rooms_detail.html
{% extends 'Dashboard/base.html' %}

{% block content %}

{% if apartment %}

<p class="card-header" style="text-transform: uppercase;"><a href="{% url 'estate_detailing'  apartment %}" style="text-decoration:none;color: green">{{ apartment.estate_name }} </a> >>>>
<!--    {{estate.id}}|-->
<!--    {{ b }}-->
     |<a href="{% url 'block_details' estate.pk  b %}" style="text-decoration:none;color: blue"> Block  {{ apartment.block }}</a> >>>> {{ apartment.flat_id }}</p>

{% if room %}
<p class="card-body"> There {{ room|pluralize:"is,are"}} {{room|length}} rooms in {{apartment.flat_id}} </p>
<p> {{ block.single_room }}</p>
<div class="row" style="overflow-x: scroll;">
    <div class="col-sm-12">
        <table class="table" >
            <thead>
                <tr>
                    <th> Room ID </th>
                    <th> Unique Room ID </th>
                    <th> Room Type </th>
                    <th> Price </th>
                </tr>
            </thead>

            <tbody>
                {% for room in room %}
                <tr>
                    <td> {{ room.room_id }}</td>
                    {% if room.unique_room_id %}
                    <td> {{room.unique_room_id }} </td>

                    <td> {{room.room_types }} </td>
                    <td> {{ room.price }}</td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% else %}
<div class="row">
    <div class="col-sm-12">
        no rooms found
    </div>
</div>

{% endif %}
{% endif %}
{% endblock content %}

House/templates/rooms/apartment_test.html
{% extends 'Dashboard/base.html' %}
{% load crispy_forms_tags bootstrap3 %}

{% block content %}
<div class="row">
    <div class="col-sm-3">

    </div>

    <div class="col-sm-6 mt-4">
            <a href="{% url 'apartment_list' estate.estate_name %}" style="text-decoration:none;color: blue">
                <p class="card-header">
                     Apartment Name: {{ apartment.estate_name }}
                </p>
            </a>
        <div style="display: flex; justify-content: space-around; margin-bottom: 20px">

            <p class="pt-4">Block: {{ apartment.block }}</p>

            <p class="pt-4"> Flat ID: <span> {{ apartment.flat_id }} </span></p>

        </div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
            <div class="row">
                <div class="col-md-3">{% bootstrap_label field.label %}</div>
                <div class="col-md-8">{% bootstrap_field field show_label=False %}</div>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-info form-control"> Update </button>
        </form>
    </div>

    <div class="col-sm-3">

    </div>
</div>

{% endblock content %}

House/templates/rooms/apartment_update.html
{% extends 'Dashboard/base.html' %}
{% load crispy_forms_tags bootstrap3 %}

{% block content %}
<div class="row">
    <div class="col-sm-4">
        <a href="{% url 'block_details' estate.pk  b %}" style="text-decoration:none;color: blue">
            <p class="card-header"> Apartment Name: {{ apartment.estate_name }}</p>
        </a>

        <p class="pt-4 pl-4" >Block: {{ apartment.block }}</p>


        {% if room.image2 %}
            <p class="mt-3"> <img src="{{ room.image2.url }}" height="200px" width="200px" style="margin-left: 20px"> </p>
        {% endif %}
        <p class="pt-4 pl-4"> Flat ID: <span> {{ apartment.flat_id }} </span></p>

    </div>

    <div class="col-sm-8 mt-4">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
            <div class="row">
                <div class="col-md-3">{% bootstrap_label field.label %}</div>
                <div class="col-md-8">{% bootstrap_field field show_label=False %}</div>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-info form-control"> Update </button>
        </form>
    </div>
</div>

{% endblock content %}

House/templates/rooms/block_details.html
{% extends 'Dashboard/base.html' %}

{% block content %}
    {% if messages %}
            {% for message in messages %}
                <div class="text-center alert alert-{{ message.tags }}" id="msg">
                    {{ message|safe }}
                </div>
            {% endfor %}
    {% endif %}
<div class="card-header">
    <a href="{% url 'estate_detailing' estate %}" style="text-decoration: none;">{{estate}}</a>|Block {{ estate.block_set.first }}
</div>

    <div class="row mt-4">
        {% if apartment %}
            {% for apartmentD in apartment %}
            <div class="col-sm-4">
                <div class="card mb-4">
                    <div class="card-body text-center">
                        <br> {{ apartmentD.flat_id|upper }}
                        {% if apartmentD.flat_id in room %}
                        <a href="{% url 'room_det' apartmentD.flat_id %}" style="text-decoration: none">
                            <div class="card-header">
                               Total room {{apartmentD.bedroom_type}}
                            </div>
                        </a>
                        {% else %}
                                <br> No Rooms Available
                               <br>
                                <a href="{% url 'apartment_update'  apartmentD.flat_id %}">
                                    <button class="btn btn-success"> Update Apartment </button>
                                </a>
                        {% endif %}
                    </div>
                    </a>
                </div>
            </div>
            {% endfor %}
        {% else %}
        <p> {{msg}}</p>
        {% endif %}

</div>
<script>
    setTimeout(function(){
        if ($('#msg').length > 0) {
            $('#msg').remove();
        }

    }, 2000);
</script>

{% endblock content %}

House/templates/rooms/booking.html
{% extends 'Dashboard/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row">
<!-- Content Column -->
    <div class="col-lg-12 mb-4">
        <!-- Illustrations -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">
                Bookings
            </h6>
            </div>
            <div class="card-body">
            {% if booking %}
            <table class="table">
                <thead>
                    <th> User </th>
                    <th> Rooms </th>
                    <th> Check IN</th>
                    <th> Check OUT</th>
                </thead>

                <tbody>
                    {% for booking in booking %}
                <tr>
                    <td> {{ booking.guest }}</td>
                    <td> {{ booking.room }}</td>
                    <td> {{ booking.check_in}}</td>
                    <td> {{ booking.check_out}}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            {% else %}
            <p>
                all booking would appear here when the time is right for reference purposes and so.
            </p>
            {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

House/templates/rooms/bookings.html
<div class="container py-5">


    <div class="table-header row">

        <div class="col-sm-12 col-md-12 col-lg-4 mb-4">
            <h2>Bookings List</h2>
        </div>

    </div>

    <table class="table table-hover table-striped">
        <thead class="bg-secondary rounded">
            <tr>
                <form action="" method="POST">
                    {% csrf_token %}
                    <th>Room Number<input type="number" min="0" name="number" value="{{number}}"
                            class="form-control border border-secondary"></th>
                    <th>Guest Name<input type="text" name="name" value="{{name}}"
                            class="form-control border border-secondary"></th>
                    <th>Date Of Reservation<input type="date" name="rez" value="{{rez}}"
                            class="form-control border border-secondary"></th>
                    <th>Start Day<input type="date" name="fd" value="{{fd}}"
                            class="form-control border border-secondary"></th>
                    <th>End Day<input type="date" name="ed" value="{{ed}}" class="form-control border border-secondary">
                    </th>
                    <th class="pb-5">Number of Dependees</th>
                    <th class="pb-5">Total amount</th>
                    <th><button type="submit" name="filter" class="btn btn-warning w-100">Filter</button></th>
                </form>

            </tr>

        </thead>
        <tbody>
            {% for b in bookings %}
            <tr>
                <td>{{b.roomNumber.number}}</td>
                <td>{{b.guest.user.first_name}}</td>
                <td>{{ b.startDate }}</td>
                <td>{{ b.endDate }}</td>
                <td>{{ b.numOfDep }}</td>
                <td>
                    {% for key, value in totals.items %}
                    {% if key == b %}
                    {{ value }}
                    {% endif %}
                    {% endfor %}
                </td>
                {% if role == "admin" or role == 'manager' %}
                <td> <a href="{% url 'deleteBooking' b.id %}"
                        class="btn btn-sm btn-outline-danger">Delete&nbsp;Booking</a></td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>

    </table>



</div>

House/templates/rooms/estate_apartment_list.html
{% extends 'Dashboard/base.html' %}
{% load crispy_forms_tags %}
{% load House_extras %}


{% block content %}
{% comment %} {% load House_extras %} {% endcomment %}

    {% if estates %}
        {% if messages %}
            {% for message in messages %}
                <div class="text-center alert alert-{{ message.tags }}" id="msg">
                    {{ message|safe }}
                </div>
            {% endfor %}
        {% endif %}
        <h3 class="card-header"> Estate List </h3>
        <p class="text-right"><a href="{% url 'estate_csv' %}"> Export To CSV </a></p>

    <div class="row" style="overflow-x: scroll;">
        <form method="get">
            <div class="col-sm-12 mt-4">
                {{ filter.form }}
                <button type="submit" class="btn btn-success"> Search </button>
            </div>
        </form>
    </div>
    <div class="row" style="overflow-x: scroll;">
        <div class="col-sm-12 mt-4">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th> Estate Name </th>
                        <th> City </th>
                        <th> Location </th>
                        <th> Block </th>
                    </tr>
                </thead>
                <tbody>
                    {% for estate in estates %}
                    <tr col-span="4">
                        <td>
                            <a href="{% url 'apartment_list' estate.estate_name %}" style="text-decoration: none">

                                <p class="card-header"> {{ estate.estate_name }} </p>
                            </a>
                        </td>
                        <td> {{ estate.city }} </td>
                        <td> {{ estate.location }} </td>
                        <td> {{ estate.block_set.count }} </td>

                    </tr>
                    {% empty %}

                    <p> no room found </p>
                    <button class="btn btn-info"><a href="{% url 'estate_listing' %}"> view all </a></button>
                    {% endfor %}
                </tbody>
            </table>

            <button class="btn btn-info" style="margin-left: 1150px"><a href="{% url 'estate_listing' %}" style="text-decoration: none" class="align: center"> show all </a></button>
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {% if estates.has_previous %}
                    <li class="page-item">
                        <a href="{% my_url 1 'page' request.GET.urlencode%}" class="page-link">&laquo; First </a>
                    </li>
                    <li class="page-item">
                        <a href="{% my_url estates.previous_page_number 'page' request.GET.urlencode %}" class="page-link"> Previous </a>
                    </li>
                    {% endif %}
                    
                    <li class="page-item">
                        <span class="page-link">
                        Page {{ estates.number}} of {{estates.paginator.num_pages}}
                        </span>
                    </li>


                    {% if estates.has_next %}
                    <li class="page-item">
                        <a href="{% my_url estates.next_page_number 'page' request.GET.urlencode %}" class="page-link"> Next</a>
                    </li>
                    <li class="page-item">
                        <a href="{% my_url estates.paginator.num_pages 'page' request.GET.urlencode %}" class="page-link">&raquo; Last</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>



    {% else %}
        <p> no estate found </p>
    {% endif %}

<script>
    setTimeout(function(){
        if ($('#msg').length > 0) {
            $('#msg').remove();
        }

    }, 2000);
</script>
{% endblock %}

House/templates/rooms/room_create_update.html
    {% extends 'Dashboard/base.html' %}
    {% load crispy_forms_tags bootstrap3 %}

    {% block content %}
    <div class="row">
    <div class="col-sm-4">
        <a href="{% url 'apartment_room_test' room.flat_id_rooms %}" style="text-decoration: none;">
            <p class="card-header"> Apartment Name: {{room.apartment_name_rooms}}</p>
        </a>
        {% if room.unique_room_id %}

        <p class="text-center">Room ID: {{room.unique_room_id }}</p>

        {% if room.image1 %}
            <img src="{{ room.image1.url }}" height="200px" width="200px" style="margin-left: 20px">
        {% endif %}

        {% if room.image2 %}
            <p class="mt-3"> <img src="{{ room.image2.url }}" height="200px" width="200px" style="margin-left: 20px"> </p>
        {% endif %}
        {% else %}
        <p class="pt-4"> Room ID: <span style="margin-left: 70px;"> {{room.room_id}} </span></p>

        {% endif %}
    </div>

    <div class="col-sm-8">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
            <div class="row">
                <div class="col-md-3">{% bootstrap_label field.label %}</div>
                <div class="col-md-8">{% bootstrap_field field show_label=False %}</div>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-info form-control"> Update </button>
        </form>
    </div>
    </div>

    {% endblock content %}